---
title: Menu Aleatorio
output: html_document
---


```{r, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE, message = FALSE)
library(pander)
set.alignment(default="left", permanent=TRUE)
```


```{r}
platos <- readr::read_csv("platos.csv")
dias   <- c("Lunes", "Martes", "Miercoles", "Jueves", "Viernes")

set.seed(1)
platos <- platos[order(runif(nrow(platos))), ]

legumbres <- platos$comida[platos$tipo == "legumbres"]
legumbres <- legumbres[which(!is.na(legumbres))]
pez       <- platos$comida[platos$tipo == "pez"]
pez       <- pez[which(!is.na(pez))]
otros     <- platos$comida[is.na(platos$tipo)]

semana1 <- otros[1:3]
semana1 <- c(semana1, pez[1], legumbres[1])[c(1, 5, 2, 4, 3)]
otros   <- otros[-c(1:3)]

semana2 <- otros[1:3]
semana2 <- c(semana2, pez[2], legumbres[2])[c(1, 5, 2, 4, 3)]
otros   <- otros[-c(1:3)]

semana3 <- otros[1:3]
semana3 <- c(semana3, pez[3], legumbres[3])[c(1, 5, 2, 4, 3)]
otros   <- otros[-c(1:3)]

semana4 <- otros[1:3]
semana4 <- c(semana4, pez[4], legumbres[1])[c(1, 5, 2, 4, 3)]
otros   <- otros[-c(1:3)]
```

```{r, results="asis"}
pander(caption="Semana 1",
  data.frame(Dia = dias, Plato = semana1)
)
```

```{r, results="asis"}
pander(caption="Semana 2",
  data.frame(Dia = dias, Plato = semana2)
)
```

```{r, results="asis"}
pander(caption="Semana 3",
  data.frame(Dia = dias, Plato = semana3)
)
```

```{r, results="asis"}
pander(caption="Semana 4",
  data.frame(Dia = dias, Plato = semana4)
)
```



